"""
Fail2ban management — jail config writer, ban management, geo-block rules.

Writes /etc/fail2ban/jail.d/webpanel-*.conf from DB rules.
Applies global geo-blocking via iptables ipset (double-protection on top of
per-domain Traefik ipDenyList rules).

Admin-only endpoints throughout.
"""
import asyncio
import ipaddress
import json
import os
import re
import subprocess
from datetime import datetime
from pathlib import Path

from fastapi import APIRouter, Depends, HTTPException
from pydantic import BaseModel
from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from app.auth import require_admin
from app.database import get_db
from app.models.fail2ban import Fail2banJail, Fail2banBan, GeoBlockRule
from app.models.country_data import CountryData

router = APIRouter(prefix="/api/fail2ban", tags=["fail2ban"])

JAIL_D_DIR  = Path(os.environ.get("FAIL2BAN_JAIL_DIR", "/etc/fail2ban/jail.d"))
IPSET_NAME  = "webpanel-geo-block"
IPTABLES_CHAIN = "WEBPANEL-GEO"

# ── Jail endpoints ─────────────────────────────────────────────────────────────

@router.get("/jails")
async def list_jails(_=Depends(require_admin), db: AsyncSession = Depends(get_db)):
    rows = (await db.execute(select(Fail2banJail).order_by(Fail2banJail.name))).scalars().all()
    return {"jails": [_jail_dict(j) for j in rows]}


def _jail_dict(j: Fail2banJail) -> dict:
    return {
        "id": j.id, "name": j.name, "enabled": j.enabled,
        "maxretry": j.maxretry, "findtime": j.findtime, "bantime": j.bantime,
        "port": j.port, "filter_name": j.filter_name, "logpath": j.logpath,
        "comment": j.comment,
        "created_at": j.created_at.isoformat() if j.created_at else None,
    }


class JailIn(BaseModel):
    name: str
    enabled: bool = True
    maxretry: int = 5
    findtime: int = 600
    bantime: int = 3600
    port: str = ""
    filter_name: str = ""
    logpath: str = ""
    comment: str = ""


@router.post("/jails")
async def create_jail(body: JailIn, _=Depends(require_admin), db: AsyncSession = Depends(get_db)):
    if not re.match(r'^[a-z0-9_\-]+$', body.name):
        raise HTTPException(400, "Jail name must be lowercase alphanumeric + hyphens/underscores")
    existing = (await db.execute(select(Fail2banJail).where(Fail2banJail.name == body.name))).scalar_one_or_none()
    if existing:
        raise HTTPException(409, f"Jail {body.name!r} already exists")
    jail = Fail2banJail(**body.model_dump())
    db.add(jail)
    await db.commit()
    await db.refresh(jail)
    await _write_jail_conf(jail)
    return _jail_dict(jail)


class JailUpdate(BaseModel):
    enabled: bool | None = None
    maxretry: int | None = None
    findtime: int | None = None
    bantime: int | None = None
    port: str | None = None
    filter_name: str | None = None
    logpath: str | None = None
    comment: str | None = None


@router.patch("/jails/{jail_id}")
async def update_jail(jail_id: int, body: JailUpdate, _=Depends(require_admin), db: AsyncSession = Depends(get_db)):
    jail = await db.get(Fail2banJail, jail_id)
    if not jail:
        raise HTTPException(404, "Jail not found")
    for k, v in body.model_dump(exclude_none=True).items():
        setattr(jail, k, v)
    jail.updated_at = datetime.utcnow()
    await db.commit()
    await _write_jail_conf(jail)
    return _jail_dict(jail)


@router.delete("/jails/{jail_id}")
async def delete_jail(jail_id: int, _=Depends(require_admin), db: AsyncSession = Depends(get_db)):
    jail = await db.get(Fail2banJail, jail_id)
    if not jail:
        raise HTTPException(404, "Jail not found")
    _remove_jail_conf(jail.name)
    await db.delete(jail)
    await db.commit()
    return {"ok": True}


# ── Conf file writer ───────────────────────────────────────────────────────────

async def _write_jail_conf(jail: Fail2banJail) -> None:
    """Write /etc/fail2ban/jail.d/webpanel-{name}.conf from a Fail2banJail row."""
    JAIL_D_DIR.mkdir(parents=True, exist_ok=True)
    conf_path = JAIL_D_DIR / f"webpanel-{jail.name}.conf"

    lines = [
        f"# Auto-generated by GnuKontrolR — do not edit manually",
        f"# Updated: {datetime.utcnow().isoformat()}",
        f"",
        f"[{jail.name}]",
        f"enabled  = {'true' if jail.enabled else 'false'}",
        f"maxretry = {jail.maxretry}",
        f"findtime = {jail.findtime}",
        f"bantime  = {jail.bantime}",
    ]
    if jail.port:
        lines.append(f"port     = {jail.port}")
    if jail.filter_name:
        lines.append(f"filter   = {jail.filter_name}")
    if jail.logpath:
        lines.append(f"logpath  = {jail.logpath}")
    if jail.comment:
        lines.append(f"# {jail.comment}")
    lines.append("")

    try:
        conf_path.write_text("\n".join(lines))
    except PermissionError:
        pass  # fail2ban dir may not be writable in dev — non-fatal

    # Reload fail2ban if running
    await _reload_fail2ban()


def _remove_jail_conf(name: str) -> None:
    conf_path = JAIL_D_DIR / f"webpanel-{name}.conf"
    try:
        conf_path.unlink(missing_ok=True)
    except PermissionError:
        pass


async def _reload_fail2ban() -> None:
    loop = asyncio.get_event_loop()
    try:
        await loop.run_in_executor(None, lambda: subprocess.run(
            ["fail2ban-client", "reload"],
            capture_output=True, timeout=10,
        ))
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass  # fail2ban not installed on this host — ignore


# ── POST /api/fail2ban/apply-all-jails ────────────────────────────────────────

@router.post("/apply-all-jails")
async def apply_all_jails(_=Depends(require_admin), db: AsyncSession = Depends(get_db)):
    """Write conf files for every jail in DB then reload fail2ban."""
    jails = (await db.execute(select(Fail2banJail))).scalars().all()
    JAIL_D_DIR.mkdir(parents=True, exist_ok=True)
    written = []
    for j in jails:
        await _write_jail_conf(j)
        written.append(j.name)
    await _reload_fail2ban()
    return {"ok": True, "written": written}


# ── Ban endpoints ──────────────────────────────────────────────────────────────

@router.get("/bans")
async def list_bans(
    active_only: bool = True,
    _=Depends(require_admin),
    db: AsyncSession = Depends(get_db),
):
    stmt = select(Fail2banBan).order_by(Fail2banBan.banned_at.desc()).limit(500)
    if active_only:
        stmt = stmt.where(Fail2banBan.active == True)
    rows = (await db.execute(stmt)).scalars().all()
    return {"bans": [_ban_dict(b) for b in rows]}


def _ban_dict(b: Fail2banBan) -> dict:
    return {
        "id": b.id, "ip": b.ip, "jail": b.jail, "reason": b.reason,
        "banned_at": b.banned_at.isoformat() if b.banned_at else None,
        "expires_at": b.expires_at.isoformat() if b.expires_at else None,
        "active": b.active, "banned_by": b.banned_by,
    }


class BanIn(BaseModel):
    ip: str
    jail: str = "webpanel-manual"
    reason: str = ""
    bantime: int = 3600   # seconds; -1 = permanent


@router.post("/bans")
async def create_ban(body: BanIn, user=Depends(require_admin), db: AsyncSession = Depends(get_db)):
    try:
        ipaddress.ip_address(body.ip)
    except ValueError:
        raise HTTPException(400, f"Invalid IP: {body.ip!r}")

    expires = None
    if body.bantime > 0:
        from datetime import timedelta
        expires = datetime.utcnow() + timedelta(seconds=body.bantime)

    ban = Fail2banBan(
        ip=body.ip, jail=body.jail, reason=body.reason,
        expires_at=expires, active=True, banned_by=f"admin:{user.id}",
    )
    db.add(ban)
    await db.commit()

    # Apply via fail2ban-client
    await _fail2ban_ban(body.ip, body.jail, body.bantime)
    return _ban_dict(ban)


@router.delete("/bans/{ban_id}")
async def unban(ban_id: int, _=Depends(require_admin), db: AsyncSession = Depends(get_db)):
    ban = await db.get(Fail2banBan, ban_id)
    if not ban:
        raise HTTPException(404, "Ban not found")
    ban.active = False
    await db.commit()
    await _fail2ban_unban(ban.ip, ban.jail)
    return {"ok": True}


async def _fail2ban_ban(ip: str, jail: str, bantime: int) -> None:
    loop = asyncio.get_event_loop()
    try:
        await loop.run_in_executor(None, lambda: subprocess.run(
            ["fail2ban-client", "set", jail, "banip", ip],
            capture_output=True, timeout=10,
        ))
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass


async def _fail2ban_unban(ip: str, jail: str) -> None:
    loop = asyncio.get_event_loop()
    try:
        await loop.run_in_executor(None, lambda: subprocess.run(
            ["fail2ban-client", "set", jail, "unbanip", ip],
            capture_output=True, timeout=10,
        ))
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass


# ── Geo-block endpoints ────────────────────────────────────────────────────────

@router.get("/geo-blocks")
async def list_geo_blocks(_=Depends(require_admin), db: AsyncSession = Depends(get_db)):
    rows = (await db.execute(
        select(GeoBlockRule).order_by(GeoBlockRule.country_name)
    )).scalars().all()
    return {"rules": [_geo_dict(r) for r in rows]}


def _geo_dict(r: GeoBlockRule) -> dict:
    return {
        "id": r.id, "country_code": r.country_code, "country_name": r.country_name,
        "blocked": r.blocked, "ipset_applied": r.ipset_applied,
        "updated_at": r.updated_at.isoformat() if r.updated_at else None,
    }


class GeoBlockIn(BaseModel):
    country_code: str   # ISO 3166-1 alpha-2
    country_name: str
    blocked: bool = True


@router.post("/geo-blocks")
async def set_geo_block(body: GeoBlockIn, _=Depends(require_admin), db: AsyncSession = Depends(get_db)):
    cc = body.country_code.upper()
    if not re.match(r'^[A-Z]{2}$', cc):
        raise HTTPException(400, "country_code must be 2-letter ISO 3166-1")

    existing = (await db.execute(
        select(GeoBlockRule).where(GeoBlockRule.country_code == cc)
    )).scalar_one_or_none()

    if existing:
        existing.blocked = body.blocked
        existing.updated_at = datetime.utcnow()
    else:
        existing = GeoBlockRule(country_code=cc, country_name=body.country_name, blocked=body.blocked)
        db.add(existing)
    await db.commit()
    await db.refresh(existing)

    # Apply or remove from ipset if block state changed
    if body.blocked:
        await _apply_geo_block(cc, db)
    else:
        await _remove_geo_block(cc, db)

    return _geo_dict(existing)


@router.post("/geo-blocks/apply-all")
async def apply_all_geo_blocks(_=Depends(require_admin), db: AsyncSession = Depends(get_db)):
    """Rebuild the iptables ipset from all blocked countries in DB."""
    blocked = (await db.execute(
        select(GeoBlockRule).where(GeoBlockRule.blocked == True)
    )).scalars().all()

    await _ensure_ipset_chain()
    applied = []
    for rule in blocked:
        cidrs = await _get_cidrs_for_country(rule.country_code, db)
        for cidr in cidrs:
            await _ipset_add(cidr)
        rule.ipset_applied = True
        applied.append(rule.country_code)

    await db.commit()
    return {"ok": True, "applied": applied}


# ── iptables / ipset helpers ───────────────────────────────────────────────────

async def _ensure_ipset_chain() -> None:
    """Create the ipset and iptables chain if they don't exist."""
    loop = asyncio.get_event_loop()

    async def _run(cmd):
        try:
            await loop.run_in_executor(None, lambda: subprocess.run(cmd, capture_output=True, timeout=10))
        except (FileNotFoundError, subprocess.TimeoutExpired):
            pass

    await _run(["ipset", "create", IPSET_NAME, "hash:net", "-exist"])
    await _run(["iptables", "-N", IPTABLES_CHAIN])
    await _run(["iptables", "-C", "INPUT", "-j", IPTABLES_CHAIN])  # check
    # If the check above fails it means the jump rule isn't there — add it
    await _run(["iptables", "-I", "INPUT", "1", "-m", "set",
                "--match-set", IPSET_NAME, "src", "-j", "DROP"])


async def _ipset_add(cidr: str) -> None:
    loop = asyncio.get_event_loop()
    try:
        await loop.run_in_executor(None, lambda: subprocess.run(
            ["ipset", "add", IPSET_NAME, cidr, "-exist"],
            capture_output=True, timeout=5,
        ))
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass


async def _ipset_del(cidr: str) -> None:
    loop = asyncio.get_event_loop()
    try:
        await loop.run_in_executor(None, lambda: subprocess.run(
            ["ipset", "del", IPSET_NAME, cidr, "-exist"],
            capture_output=True, timeout=5,
        ))
    except (FileNotFoundError, subprocess.TimeoutExpired):
        pass


async def _get_cidrs_for_country(cc: str, db: AsyncSession) -> list[str]:
    row = (await db.execute(
        select(CountryData).where(CountryData.country_code == cc.upper())
    )).scalar_one_or_none()
    if row and row.cidrs:
        return [c for c in row.cidrs.splitlines() if c.strip()]
    return []


async def _apply_geo_block(cc: str, db: AsyncSession) -> None:
    await _ensure_ipset_chain()
    cidrs = await _get_cidrs_for_country(cc, db)
    for cidr in cidrs:
        await _ipset_add(cidr)


async def _remove_geo_block(cc: str, db: AsyncSession) -> None:
    cidrs = await _get_cidrs_for_country(cc, db)
    for cidr in cidrs:
        await _ipset_del(cidr)
