"""
Local DNS management — auto-mirrors panel domains into dnsmasq so the host
(and any machine using it as a resolver) can resolve customer domains without
real public DNS delegation.

Flow:
  Domain created/deleted in panel
    → _localdns_sync() called automatically
    → Rewrites /var/webpanel/localdns/panel.hosts
    → Sends SIGHUP to webpanel_localdns container so dnsmasq reloads

Endpoints:
  GET  /api/localdns/hosts        — view current hosts file
  POST /api/localdns/sync         — force re-sync from DB (admin)
  GET  /api/localdns/setup        — returns systemd-resolved / resolv.conf config snippet
"""

import os
import signal
import logging
from pathlib import Path
from datetime import datetime, timezone

import docker
from fastapi import APIRouter, Depends, HTTPException
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select

from app.auth import get_current_user, require_admin
from app.database import get_db
from app.models.user import User
from app.models.domain import Domain

log = logging.getLogger(__name__)

router = APIRouter(prefix="/api/localdns", tags=["localdns"])

LOCALDNS_HOSTS_FILE = Path(os.getenv("LOCALDNS_HOSTS_FILE", "/var/webpanel/localdns/panel.hosts"))
LOCALDNS_CONTAINER  = "webpanel_localdns"
SERVER_IP           = os.getenv("SERVER_IP", "127.0.0.1")
PANEL_DOMAIN        = os.getenv("PANEL_DOMAIN", "")
LOCALDNS_HOST_PORT  = int(os.getenv("LOCALDNS_HOST_PORT", "5335"))


# ── Internal helper ───────────────────────────────────────────────────────────

async def _localdns_sync(db: AsyncSession) -> dict:
    """
    Regenerate panel.hosts from the domain table and reload dnsmasq.
    Called automatically on domain create/delete.
    """
    LOCALDNS_HOSTS_FILE.parent.mkdir(parents=True, exist_ok=True)

    result = await db.execute(select(Domain))
    domains = result.scalars().all()

    lines = [
        f"# Auto-generated by GnuKontrolR — {datetime.now(timezone.utc).isoformat()}",
        "# Do not edit manually; changes will be overwritten on next sync.",
        "",
    ]

    added = []
    for d in domains:
        name = d.name.lstrip("*").lstrip(".")
        lines.append(f"{SERVER_IP}  {name}")
        lines.append(f"{SERVER_IP}  www.{name}")
        lines.append(f"{SERVER_IP}  mail.{name}")
        added.append(name)

    # Always include the panel domain itself
    if PANEL_DOMAIN and PANEL_DOMAIN not in added:
        lines.append(f"{SERVER_IP}  {PANEL_DOMAIN}")
        lines.append(f"{SERVER_IP}  www.{PANEL_DOMAIN}")

    LOCALDNS_HOSTS_FILE.write_text("\n".join(lines) + "\n")
    log.info("localdns: wrote %d domain entries to %s", len(added), LOCALDNS_HOSTS_FILE)

    # Reload dnsmasq via SIGHUP
    reloaded = _reload_dnsmasq()

    return {"domains": len(added), "reloaded": reloaded}


def _reload_dnsmasq() -> bool:
    """Send SIGHUP to the localdns container so dnsmasq reloads its hosts file."""
    try:
        client = docker.from_env()
        container = client.containers.get(LOCALDNS_CONTAINER)
        container.kill(signal.SIGHUP)
        log.info("localdns: sent SIGHUP to %s", LOCALDNS_CONTAINER)
        return True
    except Exception as exc:
        log.warning("localdns: could not reload dnsmasq: %s", exc)
        return False


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get("/hosts")
async def get_hosts(_user: User = Depends(get_current_user)):
    """Return the current contents of panel.hosts."""
    if not LOCALDNS_HOSTS_FILE.exists():
        return {"content": "", "path": str(LOCALDNS_HOSTS_FILE)}
    return {
        "content": LOCALDNS_HOSTS_FILE.read_text(),
        "path": str(LOCALDNS_HOSTS_FILE),
    }


@router.post("/sync")
async def force_sync(
    db: AsyncSession = Depends(get_db),
    _admin=Depends(require_admin),
):
    """Force re-sync all domains into panel.hosts and reload dnsmasq."""
    result = await _localdns_sync(db)
    return {"ok": True, **result}


@router.get("/setup")
async def setup_instructions(
    db: AsyncSession = Depends(get_db),
    _user: User = Depends(get_current_user),
):
    """
    Returns configuration snippets so the local machine (or this server)
    uses the panel's dnsmasq for domain resolution.
    """
    result = await db.execute(select(Domain))
    domains = result.scalars().all()
    domain_names = [d.name for d in domains]
    if PANEL_DOMAIN and PANEL_DOMAIN not in domain_names:
        domain_names.insert(0, PANEL_DOMAIN)

    domain_args = " ".join(f"~{d}" for d in domain_names)

    return {
        "localdns_port": LOCALDNS_HOST_PORT,
        "server_ip": SERVER_IP,
        "panel_domain": PANEL_DOMAIN,
        "quick_test": f"dig @{SERVER_IP} -p {LOCALDNS_HOST_PORT} {PANEL_DOMAIN}",
        # ── On the SERVER itself ──────────────────────────────────────────
        "server_setup": (
            f"# Run ONCE on the server to make it resolve panel domains locally.\n"
            f"# systemd-resolved supports 'IP:port' DNS= syntax.\n"
            f"sudo mkdir -p /etc/systemd/resolved.conf.d\n"
            f"cat <<'EOF' | sudo tee /etc/systemd/resolved.conf.d/panel-localdns.conf\n"
            f"[Resolve]\n"
            f"DNS=127.0.0.1:{LOCALDNS_HOST_PORT}\n"
            f"Domains={domain_args}\n"
            f"EOF\n"
            f"sudo systemctl restart systemd-resolved\n"
            f"# Verify:\n"
            f"resolvectl query {PANEL_DOMAIN}"
        ),
        # ── On a developer's local machine ───────────────────────────────
        "local_machine_etc_hosts": (
            f"# Quick option — append to /etc/hosts on your dev machine:\n"
            f"# (Re-run after adding new domains to keep it current)\n"
            f"curl -s -H 'Authorization: Bearer <token>' "
            f"http://{SERVER_IP}:8000/api/localdns/hosts | "
            f"python3 -c \"import sys,json; print(json.load(sys.stdin)['content'])\" "
            f"| sudo tee -a /etc/hosts"
        ),
        "local_machine_dns": (
            f"# Alternative — use the panel server as your DNS resolver.\n"
            f"# Point your network's DNS to {SERVER_IP} on port {LOCALDNS_HOST_PORT}.\n"
            f"# (Works with NetworkManager, dnsmasq, or any DNS client supporting port):\n"
            f"dig @{SERVER_IP} -p {LOCALDNS_HOST_PORT} timehub.com"
        ),
        "domains": domain_names,
    }
