launch=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
gsqlite3-dnssec=yes

webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=172.30.0.0/16,127.0.0.1

api=yes
# PDNS_AUTH_API_KEY env var is picked up automatically

local-address=0.0.0.0
local-port=53
allow-recursion=172.30.0.0/16

dnsupdate=yes
log-dns-queries=no
log-dns-details=yes
