launch=gsqlite3
gsqlite3-database=/var/lib/powerdns/pdns.sqlite3
gsqlite3-dnssec=yes

webserver=yes
webserver-address=0.0.0.0
webserver-port=8081
webserver-allow-from=0.0.0.0/0

api=yes
api-key=qJV3uy_KXl-fD7RnHQdoIvZyB2DHDykaPpW3-eWZD42GRboX5nSwZWpkyndJVdJI

local-address=0.0.0.0
local-port=53

dnsupdate=yes
log-dns-queries=no
log-dns-details=yes
