#!/bin/bash
# WebPanel customer container entrypoint
# Sets up environment before starting supervisord

set -e

export DOMAIN="${DOMAIN:-localhost}"
export WEB_SERVER="${WEB_SERVER:-nginx}"
export NODE_APP="${NODE_APP:-/var/www/html/app.js}"
export NODE_ENABLED="${NODE_ENABLED:-false}"

# ── Expose DB config to PHP ──────────────────────────────────────────────────
cat > /usr/local/etc/php/conf.d/env.ini <<INI
; Auto-generated by WebPanel entrypoint
[Env]
variables_order = "EGPCS"
INI

# ── Write .env for Laravel / Node ────────────────────────────────────────────
if [ -n "$DB_HOST" ]; then
    cat > /var/www/html/.env.webpanel <<ENV
DB_HOST=${DB_HOST}
DB_DATABASE=${DB_NAME}
DB_USERNAME=${DB_USER}
DB_PASSWORD=${DB_PASS}
REDIS_URL=${REDIS_URL}
MAIL_HOST=${SMTP_HOST:-postfix}
APP_URL=https://${DOMAIN}
ENV
fi

# ── Web server selector ───────────────────────────────────────────────────────
case "$WEB_SERVER" in
    apache)
        export WEB_SERVER_IS_NGINX=false
        export WEB_SERVER_IS_APACHE=true
        export WEB_SERVER_IS_LIGHTTPD=false
        a2enmod proxy proxy_fcgi rewrite headers 2>/dev/null || true
        a2ensite 000-default 2>/dev/null || true
        ;;
    lighttpd)
        export WEB_SERVER_IS_NGINX=false
        export WEB_SERVER_IS_APACHE=false
        export WEB_SERVER_IS_LIGHTTPD=true
        mkdir -p /var/log/lighttpd
        ;;
    *)
        export WEB_SERVER_IS_NGINX=true
        export WEB_SERVER_IS_APACHE=false
        export WEB_SERVER_IS_LIGHTTPD=false
        mkdir -p /var/run/php /var/log/nginx
        ;;
esac

# ── Node.js ───────────────────────────────────────────────────────────────────
if [ "$NODE_ENABLED" = "true" ] && [ -f "$NODE_APP" ]; then
    export NODE_ENABLED=true
else
    export NODE_ENABLED=false
fi

# ── Private MariaDB initialization ───────────────────────────────────────────
# On first boot, initialize the data directory and set the root password.
# Uses the DB_PASS env var as the MySQL root password for this container.
MYSQL_DATA=/var/db/mysql
if [ ! -d "${MYSQL_DATA}/mysql" ]; then
    echo "[webpanel] Initializing private MariaDB instance..."
    mkdir -p "${MYSQL_DATA}" /var/run/mysqld
    chown -R mysql:mysql "${MYSQL_DATA}" /var/run/mysqld
    mariadb-install-db --user=mysql --datadir="${MYSQL_DATA}" --skip-test-db \
        --auth-root-authentication-method=normal > /dev/null 2>&1 || true
    # Start MariaDB temporarily to set root password
    mariadbd --user=mysql --datadir="${MYSQL_DATA}" \
        --socket=/var/run/mysqld/mysqld.sock \
        --pid-file=/var/run/mysqld/init.pid \
        --skip-networking --skip-grant-tables &
    MYSQL_INIT_PID=$!
    sleep 3
    DB_ROOT_PASS="${DB_PASS:-$(head -c 32 /dev/urandom | base64 | tr -d '/+=')}"
    mariadb --socket=/var/run/mysqld/mysqld.sock <<MSQL
FLUSH PRIVILEGES;
ALTER USER 'root'@'localhost' IDENTIFIED BY '${DB_ROOT_PASS}';
DELETE FROM mysql.user WHERE User='';
FLUSH PRIVILEGES;
MSQL
    # Store root password for container-api to use
    echo "${DB_ROOT_PASS}" > /var/db/mysql_root_pass
    chmod 600 /var/db/mysql_root_pass
    chown gnukontrolr-admin:gnukontrolr /var/db/mysql_root_pass
    kill "${MYSQL_INIT_PID}" 2>/dev/null && wait "${MYSQL_INIT_PID}" 2>/dev/null || true
    echo "[webpanel] Private MariaDB initialized."
fi
# Ensure mysqld socket dir is always available (tmpfs recreated on restart)
mkdir -p /var/run/mysqld && chown mysql:mysql /var/run/mysqld

# ── Ensure dirs ───────────────────────────────────────────────────────────────
mkdir -p /var/run/php /var/log/supervisor
chown -R www-data:www-data /var/www/html /var/customer 2>/dev/null || true

# ── webuser: domain SSH user — add to www-data group for web content access ──
# webuser can read/write /var/www/html (group gnukontrolr, mode g+w)
usermod -a -G www-data webuser 2>/dev/null || true
# Ensure webuser SSH dir is locked down (not visible to www-data)
mkdir -p /home/webuser/.ssh
chmod 700 /home/webuser
chmod 700 /home/webuser/.ssh
chown -R webuser:webuser /home/webuser
touch /home/webuser/.ssh/authorized_keys
chmod 600 /home/webuser/.ssh/authorized_keys
chown webuser:webuser /home/webuser/.ssh/authorized_keys

# ── Secure area: gnukontrolr-admin owns it, www-data cannot touch it ──────────
# gnukontrolr-admin runs the container API (port 9000) and manages /var/config.
# www-data (customer SSH/PHP) has zero access — not readable, not listable.
# Neither user is root.
chown -R gnukontrolr-admin:gnukontrolr /var/config 2>/dev/null || true
chmod -R 770 /var/config        # gnukontrolr-admin group: r/w; others: nothing
chmod 750 /var/config           # traverse for group only
chmod o-rwx /var/config         # belt-and-suspenders: no other access

# ── SSH chroot setup ──────────────────────────────────────────────────────────
# Build a minimal chroot for www-data SSH sessions.
# Inside the chroot, only /html (public_html) and /customer are bind-mounted.
# /var/config is NOT inside the chroot and is completely invisible to SSH users.
CHROOT=/var/chroot
mkdir -p "${CHROOT}/html" "${CHROOT}/customer"
# SSHD chroot requires root-owned, non-writable root of chroot
chown root:root "${CHROOT}"
chmod 755 "${CHROOT}"
# Bind-mount public_html and customer dirs into chroot (if running with privileges)
if command -v mount >/dev/null 2>&1; then
    mount --bind /var/www/html  "${CHROOT}/html"     2>/dev/null || true
    mount --bind /var/customer  "${CHROOT}/customer" 2>/dev/null || true
fi

# ── SSH setup ─────────────────────────────────────────────────────────────────
# Create privilege separation dir required by sshd
mkdir -p /run/sshd

# Generate host keys if missing (first boot)
if [ ! -f /etc/ssh/ssh_host_rsa_key ]; then
    ssh-keygen -A 2>/dev/null || true
fi

# Create www-data home + authorized_keys dir
mkdir -p /home/www-data/.ssh
chmod 700 /home/www-data/.ssh
chown www-data:www-data /home/www-data/.ssh

# Ensure gnukontrolr-admin home + SSH dir are locked down (not visible to www-data)
mkdir -p /home/gnukontrolr-admin/.ssh
chmod 700 /home/gnukontrolr-admin
chmod 700 /home/gnukontrolr-admin/.ssh
chown -R gnukontrolr-admin:gnukontrolr /home/gnukontrolr-admin
touch /home/gnukontrolr-admin/.ssh/authorized_keys
chmod 600 /home/gnukontrolr-admin/.ssh/authorized_keys
chown gnukontrolr-admin:gnukontrolr /home/gnukontrolr-admin/.ssh/authorized_keys

# If an SSH_PUBLIC_KEY env var is provided, install it
if [ -n "$SSH_PUBLIC_KEY" ]; then
    echo "$SSH_PUBLIC_KEY" > /home/www-data/.ssh/authorized_keys
    chmod 600 /home/www-data/.ssh/authorized_keys
    chown www-data:www-data /home/www-data/.ssh/authorized_keys
fi

# Generate a per-container ECDSA keypair for the customer (stored at /var/db/id_ecdsa)
if [ ! -f /var/db/id_ecdsa ]; then
    mkdir -p /var/db
    ssh-keygen -t ecdsa -b 521 -f /var/db/id_ecdsa -N "" -C "webpanel-${DOMAIN}" 2>/dev/null || true
    chmod 600 /var/db/id_ecdsa
fi

# ── Container API TLS (self-signed, internal network only) ────────────────────
# Encrypts all panel ↔ container API traffic on the Docker network.
# Traffic never leaves the internal bridge — cert verification uses pinning
# via the shared CONTAINER_API_TOKEN; the self-signed cert protects against
# passive sniffing or rogue containers on the same bridge.
if [ ! -f /var/db/api_cert.pem ]; then
    mkdir -p /var/db
    openssl req -x509 -newkey ec \
        -pkeyopt ec_paramgen_curve:P-384 \
        -keyout /var/db/api_key.pem \
        -out /var/db/api_cert.pem \
        -days 3650 -nodes \
        -subj "/CN=gnukontrolr-${DOMAIN}/O=GnuKontrolR/C=XX" \
        -addext "subjectAltName=DNS:$(hostname),IP:127.0.0.1" 2>/dev/null || true
    # gnukontrolr-admin must be able to read these (it runs the API)
    chown gnukontrolr-admin:gnukontrolr /var/db/api_cert.pem /var/db/api_key.pem 2>/dev/null || true
    chmod 640 /var/db/api_cert.pem
    chmod 600 /var/db/api_key.pem
    echo "[webpanel] Generated container API TLS certificate for ${DOMAIN}"
fi

echo "[webpanel] Starting container for domain: ${DOMAIN} (web: ${WEB_SERVER})"
exec "$@"
